import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  manifest: '/manifest.json',
  title: "InstaShop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <meta name="theme-color" content="#000000" />
      </head>
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-100 h-screen`}
    >
      <div className="lg:flex lg:items-center lg:justify-center lg:h-screen lg:bg-gray-100">
        <div className="bg-white w-full h-full lg:w-[375px] lg:h-[812px] lg:shadow-lg lg:rounded-lg lg:overflow-hidden lg:border lg:border-gray-200">
          <div className="h-full overflow-y-auto">
            {children}
          </div>
        </div>
      </div>
    </body>
  </html>
  

  );
}
